--------------------------   CRIANDO AS VIEWS   --------------------------

-- VIEW PARA FILTRAR TODOS OS PRODUTOS QUE TEM INGREDIENTES

CREATE VIEW V_PRODUTO (NOME, PREÇO, GRUPO, COMBO, INGREDIENTES) AS
	SELECT DESCRICAO, PRECO, GRP_SEQUENCIA, COMBO, INGREDIENTES
	FROM PRODUTO WHERE PRODUTO.INGREDIENTES = 'S';

-- VIEW PARA FILTRAR QUAIS PRODUTOS TEM ALGUM PEDIDO ASSOCIADO

CREATE VIEW V_PRODUTOS_NOS_PEDIDOS (NOME, PREÇO, GRUPO, COMBO, INGREDIENTES) AS
	SELECT DESCRICAO, PRECO, GRP_SEQUENCIA, PRODUTO.COMBO, INGREDIENTES
	FROM PRODUTO 
	JOIN PEDIDO_PRODUTO ON PEDIDO_PRODUTO.PRO_SEQUENCIA = PRODUTO.PRO_SEQUENCIA;

-- VIEW PARA VER AS INFORMAÇÔES DO PEDIDO DE FORMA MAIS AGRADAVEL

CREATE VIEW V_PEDIDO (NUMERO, DATA_PEDIDO, VALOR, FORMA_DE_PAGAMENTO) AS
	SELECT PED_SEQUENCIA, DATA_PEDIDO, VALOR, FORMAPAGAMENTO.DESCRICAO
	FROM PEDIDO 
	JOIN FORMAPAGAMENTO ON PEDIDO.FPG_SEQUENCIA = FORMAPAGAMENTO.FPG_SEQUENCIA;

