-- 1. Listas os paises que compraram no ano de 2014

SELECT nome FROM PAIS
	WHERE pai_codigo IN (
		SELECT PAI_CODIGO 
		FROM PEDIDO PED
		JOIN CONSUMIDOR CON USING (CON_CODIGO)
		JOIN CIDADE CID USING (CID_CODIGO)
		WHERE EXTRACT(YEAR FROM DATA_PEDIDO) = 2014
	);
	
-- 2. Listas os paises que não compraram no ao de 2011

SELECT nome FROM PAIS
	WHERE pai_codigo NOT IN (
		SELECT PAI_CODIGO 
		FROM PEDIDO PED
		JOIN CONSUMIDOR CON USING (CON_CODIGO)
		JOIN CIDADE CID USING (CID_CODIGO)
		WHERE EXTRACT(YEAR FROM DATA_PEDIDO) = 2011
	);
	
-- 3. Listar os países e cidades que não compraram em 2014.

SELECT CID.NOME, PAI.NOME 
	FROM CIDADE CID
	JOIN PAIS PAI USING (PAI_CODIGO)
	WHERE (PAI.pai_codigo, CID.cid_codigo) NOT IN (
		SELECT CID.pai_codigo, CID.cid_codigo 
		FROM PEDIDO PED
		JOIN CONSUMIDOR CON USING (CON_CODIGO)
		JOIN CIDADE CID USING (CID_CODIGO)
		WHERE EXTRACT(YEAR FROM DATA_PEDIDO) = 2014
	);

-- 4. Listar as cidades que não compraram a subcategoria “Tables”, mas compraram no ano de 2014.

SELECT NOME FROM CIDADE 
	WHERE CID_CODIGO NOT IN (
		SELECT CID_CODIGO 
		FROM ITEM ITM 
		JOIN PRODUTO PRO USING (PRO_CODIGO)
		JOIN SUBCATEGORIA SUB USING (SUB_CODIGO)
		JOIN PEDIDO USING (PED_CODIGO)
		JOIN CONSUMIDOR USING (CON_CODIGO)
		WHERE DESCRICAO = 'Tables') 
	AND CID_CODIGO IN (
		SELECT CID_CODIGO 
		FROM PEDIDO PED
		JOIN CONSUMIDOR USING (CON_CODIGO)
		WHERE EXTRACT(YEAR FROM DATA_PEDIDO) = 2014); 
		
-- 5. Listar o nome das subcategorias que mais venderam no ano de 2014

SELECT SUB.descricao, SUM(ITM.VALOR_BRUTO) 
	FROM ITEM ITM
	JOIN PRODUTO USING (PRO_CODIGO)
	JOIN SUBCATEGORIA SUB USING (SUB_CODIGO)
	JOIN PEDIDO PED USING (PED_CODIGO)
	WHERE EXTRACT(YEAR FROM DATA_PEDIDO) = 2014
	GROUP BY 1 ORDER BY 2 DESC LIMIT 5;
	
	
-- 6. Listar o nome da categoria, subcategoria e produto que mais venderam em 2014.

SELECT CAT.DESCRICAO, SUB.DESCRICAO, PRO.NOME, SUM(ITM.VALOR_BRUTO)
	FROM ITEM ITM
	JOIN PRODUTO PRO USING (PRO_CODIGO)
	JOIN SUBCATEGORIA SUB USING (SUB_CODIGO)
	JOIN CATEGORIA CAT USING (CAT_CODIGO)
	JOIN PEDIDO PED USING (PED_CODIGO)
	WHERE EXTRACT(YEAR FROM DATA_PEDIDO) = 2014
	GROUP BY 1, 2, 3 ORDER BY 4 DESC LIMIT 5;
	
	
-- 7. Listar os países e cidades que mais venderam em 2014

SELECT PAI.NOME, CID.NOME, SUM(VALOR_BRUTO)
	FROM ITEM
	JOIN PEDIDO PED USING (PED_CODIGO)
	JOIN CONSUMIDOR USING (CON_CODIGO)
	JOIN CIDADE CID USING (CID_CODIGO)
	JOIN PAIS PAI USING (PAI_CODIGO)
	GROUP BY 1, 2 ORDER BY 3 DESC LIMIT 1;
	
-- 8. Listar os países e cidades que não venderam em 2013 e venderam em 2014

SELECT PAI.NOME, CID.NOME
	FROM CIDADE CID
	JOIN PAIS PAI USING (PAI_CODIGO)
	WHERE (PAI.PAI_CODIGO, CID.CID_CODIGO) NOT IN (
		SELECT CID.PAI_CODIGO, CID.CID_CODIGO
		FROM PEDIDO PED
		JOIN CONSUMIDOR CON USING (CON_CODIGO)
		JOIN CIDADE CID USING (CID_CODIGO)
		WHERE EXTRACT(YEAR FROM DATA_PEDIDO) = 2013)
	AND (PAI.PAI_CODIGO, CID.CID_CODIGO) IN (
		SELECT CID.PAI_CODIGO, CID.CID_CODIGO
		FROM PEDIDO PED
		JOIN CONSUMIDOR CON USING (CON_CODIGO)
		JOIN CIDADE CID USING (CID_CODIGO)
		WHERE EXTRACT(YEAR FROM DATA_PEDIDO) = 2014);

-- 9. Listar os países e cidades que venderam em todos os anos

SELECT PAI.NOME, CID.NOME
	FROM CIDADE CID
	JOIN PAIS PAI USING (PAI_CODIGO)
	WHERE (PAI.PAI_CODIGO, CID.CID_CODIGO) NOT IN (
		SELECT CID.PAI_CODIGO, CID.CID_CODIGO
		FROM PEDIDO PED
		JOIN CONSUMIDOR CON USING (CON_CODIGO)
		JOIN CIDADE CID USING (CID_CODIGO)
		WHERE EXTRACT(YEAR FROM DATA_PEDIDO) = 2011)
	AND (PAI.PAI_CODIGO, CID.CID_CODIGO) IN (
		SELECT CID.PAI_CODIGO, CID.CID_CODIGO
		FROM PEDIDO PED
		JOIN CONSUMIDOR CON USING (CON_CODIGO)
		JOIN CIDADE CID USING (CID_CODIGO)
		WHERE EXTRACT(YEAR FROM DATA_PEDIDO) = 2012);
	AND (PAI.PAI_CODIGO, CID.CID_CODIGO) IN (
		SELECT CID.PAI_CODIGO, CID.CID_CODIGO
		FROM PEDIDO PED
		JOIN CONSUMIDOR CON USING (CON_CODIGO)
		JOIN CIDADE CID USING (CID_CODIGO)
		WHERE EXTRACT(YEAR FROM DATA_PEDIDO) = 2013);

-- 10. Listar os percentuais em relação ao total de vendas dos 10 países com média de vendas no ano de 2014

WITH dezmais AS (
	SELECT PAIS.NOME AS PAIS, SUM(VALOR_BRUTO) AS VALOR
	FROM ITEM
	JOIN PEDIDO USING (PED_CODIGO) 
	JOIN CONSUMIDOR USING (CON_CODIGO)
	JOIN CIDADE USING (CID_CODIGO)
	JOIN PAIS USING (PAI_CODIGO)
	WHERE EXTRACT(YEAR FROM DATA_PEDIDO) = 2014
	GROUP BY 1 ORDER BY 2 DESC LIMIT 10)
SELECT PAIS, ROUND((VALOR / (SELECT SUM(VALOR) FROM dezmais)* 100), 2) AS PERCENTUAL
	FROM dezmais;
	

-- Outros exercicios feitos com a idea do anteriores

-- 1. Listar as cidades que mais compraram no ano de 2012 e 2013

SELECT CID.NOME, SUM(ITM.VALOR_BRUTO) AS valor 
	FROM PEDIDO PED
	JOIN ITEM ITM USING (PED_CODIGO)
	JOIN CONSUMIDOR CON USING (CON_CODIGO)
	JOIN CIDADE CID USING (CID_CODIGO)
	WHERE EXTRACT(YEAR FROM DATA_PEDIDO) IN(2012, 2013)
	GROUP BY 1 ORDER BY 2 DESC 
	LIMIT 10;

-- 2. Listas as subcategorias que não tiveram vendas em 2013 e tiveram aumento de vendas em 2014

SELECT SUBCATEGORIA.DESCRICAO AS SUBCATEGORIA
	FROM SUBCATEGORIA
	WHERE SUB_CODIGO NOT IN (
		SELECT SUB_CODIGO
		FROM ITEM
		JOIN PEDIDO USING (PED_CODIGO)
		JOIN PRODUTO USING (PRO_CODIGO)
		WHERE EXTRACT(YEAR FROM DATA_PEDIDO) = 2013)
	AND SUB_CODIGO IN (
		SELECT SUB_CODIGO
		FROM ITEM
		JOIN PEDIDO USING (PED_CODIGO)
		JOIN PRODUTO USING (PRO_CODIGO)
		WHERE EXTRACT(YEAR FROM DATA_PEDIDO) = 2014);


-- 3. Listar os países que compraram pelo menos uma vez em todos os meses de 2014.

SELECT PAI.nome AS PAIS
	FROM PEDIDO PED
	JOIN CONSUMIDOR CON USING (CON_CODIGO)
	JOIN CIDADE CID USING (CID_CODIGO)
	JOIN PAIS PAI USING (PAI_CODIGO)
	WHERE EXTRACT(YEAR FROM DATA_PEDIDO) = 2014
	GROUP BY 1
	HAVING COUNT(DISTINCT EXTRACT(MONTH FROM DATA_PEDIDO)) = 12
	ORDER BY 1;
	
		
	