-- 1. Listar os países que compraram no ano de 2014.

SELECT DISTINCT PAIS.NOME AS PAIS
	FROM PEDIDO
	JOIN CONSUMIDOR ON CONSUMIDOR.CON_CODIGO = PEDIDO.CON_CODIGO
	JOIN CIDADE ON CIDADE.CID_CODIGO = CONSUMIDOR.CID_CODIGO
	JOIN PAIS ON PAIS.PAI_CODIGO = CIDADE.PAI_CODIGO
	WHERE PEDIDO.DATA_PEDIDO >= '2014-01-01' AND PEDIDO.DATA_PEDIDO <= '2014-12-31'; 

-- 2. Listar os países que não compraram no ano de 2014.

SELECT PAIS.NOME AS PAIS
	FROM PAIS
	WHERE PAIS.NOME NOT IN (
		SELECT DISTINCT PAIS.NOME AS PAIS
		FROM PEDIDO
		JOIN CONSUMIDOR ON CONSUMIDOR.CON_CODIGO = PEDIDO.CON_CODIGO
		JOIN CIDADE ON CIDADE.CID_CODIGO = CONSUMIDOR.CID_CODIGO
		JOIN PAIS ON PAIS.PAI_CODIGO = CIDADE.PAI_CODIGO
		WHERE PEDIDO.DATA_PEDIDO >= '2014-01-01' AND PEDIDO.DATA_PEDIDO <= '2014-12-31' 
	);

-- 3. Listar os países e cidades que não compraram em 2014.

SELECT CIDADE.NOME AS CIDADE, PAIS.NOME AS PAIS
	FROM CIDADE
	JOIN PAIS ON PAIS.PAI_CODIGO = CIDADE.PAI_CODIGO
	WHERE CIDADE.NOME NOT IN (
		SELECT DISTINCT CIDADE.NOME AS CIDADE
		FROM PEDIDO
		JOIN CONSUMIDOR ON CONSUMIDOR.CON_CODIGO = PEDIDO.CON_CODIGO
		JOIN CIDADE ON CIDADE.CID_CODIGO = CONSUMIDOR.CID_CODIGO
		WHERE PEDIDO.DATA_PEDIDO >= '2014-01-01' AND PEDIDO.DATA_PEDIDO <= '2014-12-31' 
	)
	ORDER BY PAIS.NOME, CIDADE.NOME;


-- 4.  Listar as cidades que não compraram a categoria “Technology”, mas compraram no ano de 2014.

SELECT DISTINCT CIDADE.NOME AS CIDADE
	FROM CIDADE
	WHERE CIDADE.NOME NOT IN (
		SELECT DISTINCT CIDADE.NOME AS CIDADE
		FROM PEDIDO
		JOIN CONSUMIDOR ON CONSUMIDOR.CON_CODIGO = PEDIDO.CON_CODIGO
		JOIN CIDADE ON CIDADE.CID_CODIGO = CONSUMIDOR.CID_CODIGO
		JOIN ITEM ON ITEM.PED_CODIGO = PEDIDO.PED_CODIGO
		JOIN PRODUTO ON PRODUTO.PRO_CODIGO = ITEM.PRO_CODIGO
		JOIN SUBCATEGORIA ON SUBCATEGORIA.SUB_CODIGO = PRODUTO.SUB_CODIGO
		JOIN CATEGORIA ON CATEGORIA.CAT_CODIGO = SUBCATEGORIA.CAT_CODIGO
		WHERE CATEGORIA.DESCRICAO = 'Technology'
	)  ORDER BY CIDADE.NOME
INTERSECT
SELECT DISTINCT CIDADE.NOME AS CIDADE 
		FROM PEDIDO
		JOIN CONSUMIDOR ON CONSUMIDOR.CON_CODIGO = PEDIDO.CON_CODIGO
		JOIN CIDADE ON CIDADE.CID_CODIGO = CONSUMIDOR.CID_CODIGO
		WHERE PEDIDO.DATA_PEDIDO BETWEEN '2014-01-01' AND '2014-12-31';

