-- 1. Listar as siglas de origem dos aeroportos no ano de 2021.(Restrição)

SELECT DISTINCT AEROPORTO.SIGLA 
FROM PERIODO
INNER JOIN AEROPORTO ON PERIODO.AER_ORG_CODIGO = AEROPORTO.AER_CODIGO
WHERE ANO = 2021;

-- 2. Listar as companhias que voaram no ano de 2021 com voos destinados aos aeroportos na Europa. (Junção)

SELECT DISTINCT EMPRESA.NOME AS COMPANHIA
FROM PERIODO
INNER JOIN EMPRESA ON EMPRESA.EMP_CODIGO = PERIODO.EMP_CODIGO
INNER JOIN AEROPORTO ON AEROPORTO.AER_CODIGO = PERIODO.AER_DST_CODIGO
INNER JOIN PAIS ON PAIS.PAI_CODIGO = AEROPORTO.PAI_CODIGO
INNER JOIN CONTINENTE ON CONTINENTE.CNT_CODIGO = PAIS.CNT_CODIGO
WHERE PERIODO.ANO = 2021 AND CONTINENTE.CNT_CODIGO = 2;

-- Listar o nome das companhias que voaram em 2021 e dos países que tiveram voos em 2020. (União)



SELECT * FROM aeroporto;
SELECT * FROM continente;
SELECT * FROM empresa;
SELECT * FROM grupo;
SELECT * FROM nacionalidade;
SELECT * FROM natureza;
SELECT * FROM pais;
SELECT * FROM periodo;